version: "3"
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    tty: true
    restart: always
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
